version: "3.9"

services:
  db:
    container_name: parksoft-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    networks:
      - parksoft-network
    volumes:
      - ./Infrastructure/Data/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  migration:
    container_name: parksoft-migration
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - parksoft-network
    environment:
      ConnectionStrings__DefaultConnection: Server=db;Database=ParkSoftDB;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=True;TrustServerCertificate=True
    command: >
      /bin/sh -c "
      until /opt/mssql-tools/bin/sqlcmd -S db -U sa -P YourStrong@Passw0rd -Q 'SELECT 1' > /dev/null 2>&1; do
        echo 'Waiting for SQL Server to be ready...';
        sleep 5;
      done &&
      dotnet ef database update --project Infrastructure --startup-project WebUI
      "

  webapp:
    container_name: parksoft-webapp
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - migration
    ports:
      - "8081:80"
    environment:
      ConnectionStrings__DefaultConnection: Server=db;Database=ParkSoftDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    networks:
      - parksoft-network
    volumes:
      - ./publish/wwwroot:/app/wwwroot

networks:
  parksoft-network:
    driver: bridge
